# Optional QAIRT overrides. Packaged pins live in /usr/lib/dragon-q8b/qnn.conf
# and are replaced when dragon-q8b-qnn is updated. Uncomment to pin a different
# official Community Edition archive on this machine.
# QAIRT_VERSION=
# QAIRT_DOWNLOAD_URL=
# QAIRT_ARCHIVE_SHA256=
# QAIRT_LICENSE_SHA256=
# QAIRT_TARGET=aarch64-oe-linux-gcc11.2
# QAIRT_DSP_ARCH=68
